### ISSUE TITLE
Add SWOT L2 Collections to HiTIDE

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#1]
Here's the official SWOT L2 Collections list to add to HiTIDE:

SWOT_L2_NALT_IGDR_SSHA_1.0
SWOT_L2_NALT_OGDR_SSHA_1.0
SWOT_L2_LR_SSH_BASIC_1.0
SWOT_L2_LR_SSH_EXPERT_1.0
SWOT_L2_LR_SSH_WINDWAVE_1.0

Can NOT do:

SWOT_L2_NALT_GDR_SSHA_1.0  (No data yet)
SWOT_L2_LR_SSH_UNSMOOTHED_1.0   (Footprint issues, will revisit in a future PI)

**Comment by davidcolemanjpl** [comment]
HiTIDE-UI (UAT)  VERSION 4.15.1-2-
HiTIDE Profile v4.9.8-rc.1
L2SS-py v2.5.0rc9
HiTIDE backfill tool v0.3.3
 
NOTE: tested following cloud SWOT L2 sub-collections
SWOT_L2_LR_SSH_UNSMOOTHED_1.0 – 30 matching granules - granule images and footprints do NOT display on map in UI as expected; Download Submission Failed
 
SWOT_L2_LR_SSH_BASIC_1.0 – 28 matching granules - Download Submission Failed
SWOT_L2_LR_SSH_EXPERT_1.0 – 28 matching granules - Download Submission Failed
SWOT_L2_LR_SSH_WINDWAVE_1.0 – 28 matching granules - Download Submission Failed
SWOT_L2_NALT_IGDR_SSHA_1.0 – 23 matching granules - PASS

SWOT_L2_NALT_OGDR_SSHA_1.0 – 16 matching granules - PASS
 
NOTE2: 
SWOT_L2_NALT_GDR_SSHA_1.0 – 0 matching granules

**Comment by davidcolemanjpl** [comment]
@jamesfwood what is the current version of concise that's  in UAT?

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (**UAT**) - v4.15.0-RC.8
l2ss-py:2.5.0rc10
HiTIDE Profile v4.9.8-rc.1
podaac/concise:**uat**

Verified that the following SWOT_L2 cloud sub-collections currently function as expected in HiTIDE-UI:

**SWOT_L2_NALT_IGDR_SSHA_1.0 
SWOT_L2_NALT_OGDR_SSHA_1.0
SWOT_L2_LR_SSH_BASIC_1.0
SWOT_L2_LR_SSH_EXPERT_1.0
SWOT_L2_LR_SSH_WINDWAVE_1.0**


NOTE:
Current issues w/ other respective SWOT_L2 sub-collections in HiTIDE:

**SWOT_L2_NALT_GDR_SSHA_1.0** (Currently, no data for dataset)

**SWOT_L2_LR_SSH_UNSMOOTHED_1.0** (will plan on revisiting the footprint issues "in a future PI")
note: this dataset also fails when using merge granules (concise): 
_WorkItem [3445918] failed with error: podaac/concise:uat: Service request failed with an unknown error_ (see Harmony jobID 72a1f2ac-98d9-411c-9820-be9b9097ee47)
