### ISSUE TITLE
Add new SWOT 1.1 associations to Hitide, l2ss-py, concise, etc

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#15]
Add collections to HiTIDE:

SWOT_L2_LR_SSH_BASIC_1.1
SWOT_L2_LR_SSH_EXPERT_1.1
SWOT_L2_LR_SSH_WINDWAVE_1.1

This includes adding functionality to run subsetting (L2ss-py), merging (l2ss-py with concise), and include footprints and thumbnail images, and Collection Info in HiTIDE fully complete and correct.

**Comment by davidcolemanjpl** [comment]
HiTIDE UI v4.16.1-RC.1
HiTIDE Profile v4.10.0-rc.1
l2ss-py:2.7.0rc1
CONCISE v0.7.0rc7

**_Test Complete_**


https://cae-testrail.jpl.nasa.gov/testrail/index.php?/tests/view/7711632&group_by=cases:title&group_order=asc&group_id=-1
