### ISSUE TITLE
Release Backfill-Tool v0.4.0

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#25]
Release Backfill Tool v0.4.0 to also deploy to new forge and tig to Cumulus AWS

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test backfill-tool v0.4.0rc4 in UAT.  It includes tig 0.7.0-rc.3 and forge 0.8.0-rc.2.
Thanks!

**Comment by davidcolemanjpl** [comment]
podaac-hitide-backfill-tool 0.4.0rc4
podaac-app-services-uat-1858
TIG v0.7.0-rc.3
FORGE v0.8.0-rc.2


Utilized **_VIIRS_NPP-NAVO-L2P-v1.0_** cloud dataset 
TIG and FORGE workflows appear to succeed as expected in the services-uat env.

 
note: The anomaly documented in PODAAC-5820 still exists in this hitide-backfill-tool version (_Partial PASS_)


SIDE Observation: (_Conditional PASS_):
Even though TIG workflow execution succeeded, observed an error in the execution output:
(Can see recent podaac-services-uat-hitide-backfill-tig execution: c6465d60-690a-4a84-8626-a3a024ea4cdb)

"errorType": "Error",
    "errorMessage": "Failed to ingest, statusCode: 409, statusMessage: Conflict, CMR error message: [\"Expected revision-id of [17] got [16] for [G1241754616-POCLOUD]\"]",
    "trace": [
      "Error: Failed to ingest, statusCode: 409, statusMessage: Conflict, CMR error message: [\"Expected revision-id of [17] got [16] for [G1241754616-POCLOUD]\"]",
      "    at CMR.ingestUMMGranule (/var/task/webpack:/src/CMR.ts:305:13)",
      "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
    ]
  },
  "exception": "None"
}

**Comment by davidcolemanjpl** [comment]
podaac-hitide-backfill-tool 0.4.0rc4
podaac-app-services-uat-1858
TIG v0.7.0-rc.3
FORGE v0.8.0-rc.2

Utilized **MODIS_T-JPL-L2P-v2019.0** cloud dataset

note: The anomaly documented in **PODAAC-5820** still exists in this hitide-backfill-tool version (Partial PASS)


**_SIDE Observation_**: (Conditional PASS)
Even though TIG / FORGE workflow executions succeeded, observed errors related to revision-id in the execution output:

see **FORGE** Execution: a23f56a1-1129-4bdc-8121-6dcb10deeda2

"errorType": "Error",
"errorMessage": "Failed to ingest, statusCode: 409, statusMessage: Conflict, CMR error message: [\"Expected revision-id of [14] got [13] for [G1236584623-POCLOUD]\"]",
"trace": [
  "Error: Failed to ingest, statusCode: 409, statusMessage: Conflict, CMR error message: [\"Expected revision-id of [14] got [13] for [G1236584623-POCLOUD]\"]",
  "    at CMR.ingestUMMGranule (/var/task/webpack:/src/CMR.ts:305:13)",
  "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
]
}
}


see recent **TIG** Executions: 
da603f82-6bfb-493d-a26f-c334cd56d89d or 395f17e5-339a-4a5d-a119-b218830a6cfc

"errorType": "Error",
"errorMessage": "Failed to ingest, statusCode: 409, statusMessage: Conflict, CMR error message: [\"Expected revision-id of [14] got [13] for [G1236933498-POCLOUD]\"]",
"trace": [
  "Error: Failed to ingest, statusCode: 409, statusMessage: Conflict, CMR error message: [\"Expected revision-id of [14] got [13] for [G1236933498-POCLOUD]\"]",
  "    at CMR.ingestUMMGranule (/var/task/webpack:/src/CMR.ts:305:13)",
  "    at processTicksAndRejections (internal/process/task_queues.js:97:5)"
]
},



**Test Complete**
