### ISSUE TITLE
Remove all "XXXXX-PODAAC" collections from HiTIDE

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#27]
HiTIDE POCLOUD shouldn't contain any collections that end in **-PODAAC**.

Verify here:
https://cmr.earthdata.nasa.gov/search/tools.umm_json?name=hitide&pretty=true&provider=pocloud

and in the HiTIDE UI

**Comment by davidcolemanjpl** [comment]
_HiTIDE UI (UAT)  v 4.16.1-RC.1_
(https://cmr.uat.earthdata.nasa.gov/search/tools.umm_json?name=hitide&pretty=true&provider=pocloud)
_HiTIDE UI (OPS) v4.16.1_ 
(https://cmr.earthdata.nasa.gov/search/tools.umm_json?name=hitide&pretty=true&provider=pocloud)


Verified in HiTIDE UI  (and CMR) that the on-prem (- PODAAC) collection / concept-id references have been removed accordingly.

**_Test Complete_**
