### ISSUE TITLE
Enable collections in cumulus-configurations

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#28]
Details defined here:

https://jira.jpl.nasa.gov/browse/PODAAC-5927

Being done by I&A, Stepheny.

**Comment by jamesfwood** [comment]
@davidcolemanjpl please verify the collections in here:
https://jira.jpl.nasa.gov/browse/PODAAC-5927
are complete.  Excluding the 4 Jason S6 collections

**Comment by davidcolemanjpl** [comment]
CYGNSS_L2_SURFACE_FLUX_V2.0 - not in UAT env

**Comment by jamesfwood** [comment]
@davidcolemanjpl don't worry about testing this ticket.  I'll create a new one that is more detailed for you to test.

**Comment by davidcolemanjpl** [comment]
FYI, After initial review in Cumulus UAT (_Deploy (tf) v11.2.0_) - POCLOUD

Per the testable collections noted in PODAAC-5927, the following collections only has image (TIG) enabled. 
Footprint not currently enabled in collection definition:

**CYGNSS_L2_SURFACE_FLUX_V2.0** --  (image only) -– footprint not enabled for collection
**JASON_CS_S6A_L2_ALT_HR_RED_OST_STC_F** -- (image only) – footprint not enabled for collection
**JASON_CS_S6A_L2_ALT_HR_STD_OST_STC_F** -- (image only) – footprint not currently enabled for collection
**JASON_CS_S6A_L2_ALT_LR_RED_OST_STC_F** --  (image only) – footprint not currently enabled for collection
**JASON_CS_S6A_L2_ALT_LR_STD_OST_STC_F** - (image only) – footprint not currently enabled for collection
**JASON_CS_S6A_L2_AMR_RAD_NRT** - (image only) – footprint not currently enabled for collection
**JASON_CS_S6A_L2_AMR_RAD_STC** -- (image only) – footprint not currently enabled for collection
