### ISSUE TITLE
Backfill collections in Phase 8

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#29]
Run Phase 8:
https://wiki.jpl.nasa.gov/display/PD/Backfilling+Progress+Report

**Comment by jamesfwood** [comment]
Added more collections to Phase 8.  Thank you!

**Comment by ymchenjpl** [comment]
All 29 collections have been finished per our wiki page: 
https://wiki.jpl.nasa.gov/display/PD/Services+HiTIDE-Backfill+Tool+v0.4.0+Services+OPS+Backfill+Deployment+Procedure+-+10-24-2023
