### ISSUE TITLE
Release Backfill Tool v0.4.1

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#33]
Release Backfill Tool v0.4.1
Includes new:
forge 0.9.0
tig 0.8.0

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test in UAT

**Comment by davidcolemanjpl** [comment]
_podaac-hitide-backfill-tool v0.4.1rc6
podaac-app-services-uat-1858
TIG v0.8.0 / FORGE v0.9.0
HiTIDE-UI (UAT) - v4.16.1-RC.1_


**_Test Complete_**
