### ISSUE TITLE
Test SWOT_L2_LR_SSH_EXPERT_1.0 and SWOT_L2_LR_SSH_EXPERT_1.1 ssha_karin_2 correction thumbnail

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#34]
Use the backfill tool to update some SWOT_L2_LR_SSH_EXPERT 1.0 and 1.1 granules and produce the new thumbnail image for ssha_karin_2.  This image should be a high resolution image and should be verified with Jinbo that it is correct.

**Comment by sliu008** [comment]
- Test make sure ssha_karin_2 is generated
- Image should be visible in hitide
- Check to see in cmr should be able to download and size is bigger than other images and so is resolution

**Comment by davidcolemanjpl** [comment]
Please list / include the specific version(s) under test.

E.g., 
HiTIDE Backfill tool version 
TIG version 
etc

**Comment by davidcolemanjpl** [comment]
**podaac-hitide-backfill-tool v0.4.1rc6
HiTIDE-UI (UAT) - v4.16.1-RC.1
TIG v0.8.0**



**_Test Complete_**


Sample of generated granules for **SWOT_L2_LR_SSH_EXPERT_1.0**:

SWOT_L2_LR_SSH_Expert_495_015_20230419T064442_20230419T073147_PIA1_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1256122852-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_495_015_20230419T064442_20230419T073147_PIA1_01_swot&pg[0][gsk]=-start_date&g=G1257442101-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.0&tl=1702512484.866!3!!&lat=0.0000649999999993156&zoom=1

SWOT_L2_LR_SSH_Expert_495_014_20230419T055111_20230419T063649_PIA1_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1256122852-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_495_014_20230419T055111_20230419T063649_PIA1_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.0&tl=1702512484.866!3!!&lat=0.0000649999999993156&zoom=1

SWOT_L2_LR_SSH_Expert_495_016_20230419T073146_20230419T081808_PIA1_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1256122852-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_495_016_20230419T073146_20230419T081808_PIA1_01_swot&pg[0][gsk]=-start_date&g=G1257442102-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.0&tl=1702512484.866!3!!&lat=0.0000649999999993156&zoom=1

SWOT_L2_LR_SSH_Expert_495_011_20230419T031617_20230419T040724_PIA1_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1256122852-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_495_011_20230419T031617_20230419T040724_PIA1_01_swot&pg[0][gsk]=-start_date&g=G1257442097-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.0&tl=1702512484!3!!&lat=0.0000649999999993156&zoom=1

SWOT_L2_LR_SSH_Basic_495_004_20230418T211838_20230418T220751_PIA1_01:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1256122852-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_495_004_20230418T211838_20230418T220751_PIA1_01_swot&pg[0][gsk]=-start_date&g=G1257442090-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.0&tl=1702512484!3!!&lat=0.0000649999999993156&zoom=1



Some granules for **SWOT_L2_LR_SSH_EXPERT_1.1**:

SWOT_L2_LR_SSH_Expert_485_007_20230409T012737_20230409T021559_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_007_20230409T012737_20230409T021559_PIB0_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_017_20230409T100130_20230409T104738_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_017_20230409T100130_20230409T104738_PIB0_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_010_20230409T035852_20230409T044958_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_010_20230409T035852_20230409T044958_PIB0_01_swot&pg[0][gsk]=-start_date&g=G1259972475-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_001_20230408T201901_20230408T211008_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_001_20230408T201901_20230408T211008_PIB0_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_019_20230409T114417_20230409T122914_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_019_20230409T114417_20230409T122914_PIB0_01_swot&pg[0][gsk]=-start_date&g=G1259972502-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_013_20230409T063315_20230409T072213_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_013_20230409T063315_20230409T072213_PIB0_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_011_20230409T044957_20230409T054105_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_011_20230409T044957_20230409T054105_PIB0_01_swot&pg[0][gsk]=-start_date&g=G1259972478-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_018_20230409T104737_20230409T113443_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_018_20230409T104737_20230409T113443_PIB0_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942.793!3!!&lat=0.00004500000000007276&zoom=0

SWOT_L2_LR_SSH_Expert_485_014_20230409T072451_20230409T081030_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_014_20230409T072451_20230409T081030_PIB0_01_swot&pg[0][gsk]=-start_date&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942!3!!

SWOT_L2_LR_SSH_Expert_485_012_20230409T054104_20230409T062640_PIB0_01_swot:
https://search.uat.earthdata.nasa.gov/search/granules?p=C1259115166-POCLOUD&pg[0][v]=f&pg[0][id]=SWOT_L2_LR_SSH_Expert_485_012_20230409T054104_20230409T062640_PIB0_01_swot&pg[0][gsk]=-start_date&g=G1259972481-POCLOUD&q=SWOT_L2_LR_SSH_EXPERT_1.1&tl=1702582942!3!!
