### ISSUE TITLE
SWOT 2.0 collections: Fix thumbnail alignment with footprint

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#36]
The thumbnail should be inside the footprint.

Collections include:

SWOT_L2_LR_SSH_BASIC_2.0
SWOT_L2_LR_SSH_EXPERT_2.0
SWOT_L2_LR_SSH_WINDWAVE_2.0

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (UAT) v4.17.0-RC.6
l2ss-py:v2.8.0rc3
concise:v0.8.0rc1

SWOT_L2 collection thumbnail images are properly aligned inside the footprints as expected:


SWOT_L2_LR_SSH_BASIC_2.0 - **_PASS_** 
SWOT_L2_LR_SSH_EXPERT_2.0 - **_PASS_**
SWOT_L2_LR_SSH_WINDWAVE_2.0 - **_PASS_**
