### ISSUE TITLE
Remove UMM-G bounding box in HiTIDE collections when GPoloygon exists

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#40]
Collection List details here:

https://jira.jpl.nasa.gov/browse/PODAAC-6117

Work done by Jack, but Jim may try to help to get this done sooner.

**Comment by jjmcnelis** [comment]
Jira ticket for @jamesfwood https://jira.jpl.nasa.gov/browse/PODAAC-6117

**Comment by jamesfwood** [comment]
Check Progress here:
https://docs.google.com/spreadsheets/d/1wQKtqMo3xsmEV-Z-_Voc6dHh06ofukpnp5AAE9i8FPw/edit?usp=sharing
Use latest Monthly Counts sheet

**Comment by jamesfwood** [comment]
All done!
