### ISSUE TITLE
THREDDS Cloud evaluation

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#42]
Talk with Curtis

Ed Armstrong too.

Joe Roberts

Reach out to company (Unidata)

Haley Johnson (Unidata)

Wikio?

**Comment by jimmie** [comment]
Capturing Curtis' comments: 

Yes, a while back last year Mike Gangl and I were trying to get THREDDS working in AWS NGAP environment. It was kind of working except there were performance issues (sometimes processes would timeout). I created and configured the AWS resources using terraform which was triggered by a Jenkins pipeline job. The AWS architecture includes a built THREDDS docker image stored in ECR, container services using ECS, EFS and S3 for storage, an ALB, and lambda function that syncs collection configuration and data files.
 
JPL Github Source: https://github.jpl.nasa.gov/podaac/thredds-ngap
 
Jenkins pipelines: https://devops1.jpl.nasa.gov:8443/job/THREDDS/job/PODAAC_THREDDS_CI/
https://devops1.jpl.nasa.gov:8443/job/THREDDS/

**Comment by jamesfwood** [comment]
Stopping tracking this here
