### ISSUE TITLE
Enable SWOT 2.0 collections in Cumulus to process footprints and thumbnails in forward processing

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#47]
Tracking this ticket for @skorper 

https://jira.jpl.nasa.gov/browse/PODAAC-6094

**Comment by ymchenjpl** [comment]
Stepheny enabled Footprint workflow in the SWOT OPS Cumulus Forward-stream V2.0 collection definitions on 1/29/24 (see Jira Ticket https://jira.jpl.nasa.gov/browse/PODAAC-6094)
Ying created daily cronjob to run the Backfill tool for the V2.0 collections that need Thumbnails.
