### ISSUE TITLE
Backfill SWOT NALT collections so all parent and sub collections have footprints

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#48]

**Comment by ymchenjpl** [comment]
The backfilling for SWOT_L2_NALT_GDR_2.0 Parent collection and the Sub-collections: SWOT_L2_NALT_GDR_GDR_2.0,
SWOT_L2_NALT_GDR_SGDR_2.0, and SWOT_L2_NALT_GDR_SSHA_2.0 has been completed.  Includes granules for Cycles 1-5 and Cycles 400-578 (see OPS backfilling wiki page at: https://wiki.jpl.nasa.gov/display/PD/Services+HiTIDE-Backfill+Tool+v0.4.1+Services+OPS+Backfill+Deployment+Procedure+-+01-29-2024
