### ISSUE TITLE
Associate SWOT 2.0 collections with HiTIDE tool

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#52]
Associate to HiTIDE Tool:
SWOT_L2_LR_SSH_BASIC_2.0
SWOT_L2_LR_SSH_EXPERT_2.0
SWOT_L2_LR_SSH_WINDWAVE_2.0

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test the 3 collections above in HiTIDE UAT.
Thanks!

**Comment by davidcolemanjpl** [comment]
...Will plan on re-testing the  SWOT_L2_LR collections in HiTIDE UAT:

note: these Collections tested recently in HiTIDE UAT: 
https://github.com/podaac/hitide/issues/51#issuecomment-1958598876


_SWOT_L2_LR_SSH_BASIC_2.0
SWOT_L2_LR_SSH_EXPERT_2.0
SWOT_L2_LR_SSH_WINDWAVE_2.0_

**Comment by davidcolemanjpl** [comment]
**HiTIDE UI (UAT)** v4.17.0-RC.6
HiTIDE-Profile v4.10.0-rc.1
l2ss-py v2.8.0rc3
CONCISE v0.8.0rc1


**SWOT_L2_LR_SSH_BASIC_2.0** - _PASS_
See recent Harmony UAT job(s):
[https://harmony.uat.earthdata.nasa.gov/jobs/](https://harmony.uat.earthdata.nasa.gov/jobs/a477617d-ff57-415c-b970-9fdfefb38be4)[6df6db72-c3f2-466e-94cd-dc5c86b0ae24](https://harmony.uat.earthdata.nasa.gov/workflow-ui/6df6db72-c3f2-466e-94cd-dc5c86b0ae24?fromDateTime=&toDateTime=&dateKind=createdAt&tzOffsetMinutes=)
or
https://harmony.uat.earthdata.nasa.gov/jobs/a477617d-ff57-415c-b970-9fdfefb38be4


**SWOT_L2_LR_SSH_EXPERT_2.0** - _PASS_
See recent Harmony UAT job(s):
https://harmony.uat.earthdata.nasa.gov/jobs/14e91b3f-41e4-4800-8cf6-e87eef3c6ea9
or
[https://harmony.uat.earthdata.nasa.gov/jobs/f6a975b3-4231-4192-a691-73605214609](https://harmony.uat.earthdata.nasa.gov/jobs/f6a975b3-4231-4192-a691-73605214609a)


**SWOT_L2_LR_SSH_WINDWAVE_2.0** -  _PASS_
See recent Harmony UAT job:
https://harmony.uat.earthdata.nasa.gov/jobs/8f614131-248b-4a15-b970-132a547e706e
