### ISSUE TITLE
Test SWOT 2.0 Collections in HiTIDE (info, footprints, thumbs, subsetting, concise, etc)

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#53]
Test in HiTIDE:
SWOT_L2_LR_SSH_BASIC_2.0
SWOT_L2_LR_SSH_EXPERT_2.0
SWOT_L2_LR_SSH_WINDWAVE_2.0

**Comment by jamesfwood** [comment]
Hi @davidcolemanjpl Please test everything in HiTIDE UAT and OPS for the above collections.
Thanks!

**Comment by davidcolemanjpl** [comment]
**_Test Complete_** 


**HiTIDE (UAT)**:
HiTIDE UI (UAT) v4.17.0-RC.6
L2SS-py v2.9.0rc1
CONCISE v0.8.0rc1
HiTIDE Profile v4.10.0-rc.1
Harmony (UAT) v 0.0.988


SWOT_L2_LR_SSH_BASIC_2.0 - 
See harmony Job status https://harmony.uat.earthdata.nasa.gov/jobs/ebf9cd84-efa8-46ad-b663-9bbf30a2c520

SWOT_L2_LR_SSH_EXPERT_2.0 - 
See harmony Job status https://harmony.uat.earthdata.nasa.gov/jobs/7b30c091-50df-4bbc-82eb-30521a427223

SWOT_L2_LR_SSH_WINDWAVE_2.0 - 
See Harmony Job status  https://harmony.uat.earthdata.nasa.gov/jobs/0ef6a7f5-e801-427d-a747-f6fb66b46050



**HiTIDE (OPS)**:
HiTIDE UI (OPS) v4.17.0
L2SS-py v2.8.0
CONCISE  v0.7.0
HiTIDE Profile v4.10.0
Harmony UI (OPS) v0.0.988

SWOT_L2_LR_SSH_BASIC_2.0 - 
See Harmony Job status  https://harmony.earthdata.nasa.gov/jobs/557f3ce5-04a4-41e9-9052-07a3ba30640f

SWOT_L2_LR_SSH_EXPERT_2.0 - 
See harmony Job status  https://harmony.earthdata.nasa.gov/jobs/5fad7171-9b21-4bcf-b436-fc6cf6f95942

SWOT_L2_LR_SSH_WINDWAVE_2.0 - 
See Harmony Job status  https://harmony.earthdata.nasa.gov/jobs/76c85b74-9156-4def-a825-0cb5955540b1



_Side-Observation:_
The Metadata & Granule Availability Images (dataset info icon) are different images when comparing the (3) SWOT_L2_LR collections in UAT vs OPS.
(See attached 'SWOT_L2_LR_SSH_WINDWAVE_2.0' image example)
issue related to  https://github.com/podaac/hitide-ui/issues/42

HiTIDE UI (UAT) Image:
![SWOT_L2_LR_SSH_WINDWAVE_2 0 -UAT UI pic](https://github.com/podaac/hitide/assets/57456095/4bc375ad-975a-430e-b6f3-7d3408c110e1)

HiTIDE UI (OPS) Image:
![SWOT_L2_LR_SSH_WINDWAVE_2 0 -OPS UI pic ](https://github.com/podaac/hitide/assets/57456095/9b11b341-1047-4f1f-8e12-a4b0dcbb0c06)

**Comment by davidcolemanjpl** [comment]
HiTIDE (**UAT**):
HiTIDE UI (**UAT**) v4.17.0-RC.6

**_UPDATE/NOTE_**:
Today, it appears that the Metadata & Granule Availability Images (dataset info icon) now display in HiTIDE UI UAT accordingly for the respective SWOT_L2_LR collections
