### ISSUE TITLE
Automate the Github Actions UMM-V Sync so it syncs all HiTIDE Collections from OPS to UAT nightly

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#55]
Run this nightly on all collections and auto sync missing UAT UMM-V:

https://devops1.jpl.nasa.gov:8443/job/Data_Transformation_Visualization_Analysis/job/tva-automation-tools/job/UMM_V_SYNC/

**Comment by sliu008** [comment]
https://github.com/podaac/tva-automation-tools/tree/main/umm_v_auto
