### ISSUE TITLE
Investigate why SMAP_RSS_L2_SSS_V5 is not generating image and footprint in Cumulus foward-processing

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#56]
Investigate in OPS

**Comment by ymchenjpl** [comment]
Asked Stepheny and Nick to investigate the changes that were deployed to Cumulus OPS for the cut-over for collection SMAP_RSS_L2_SSS_V5 which appears to have accidentally reverted the Forge & TIG choices:
I saw check-ins to enable Forge & TIG :
https://github.jpl.nasa.gov/podaac/cumulus-configurations/commit/e0e45c75136ccb87500df7890cd40a147550ac40
But in Cumulus OPS Dashboard, I see these old workflow choices:
		"workflowChoice": {
			"compressed": false,
			"convertNetCDF": false,
			"dmrpp": true,
			"glacier": true,
			"readDataFileForMetadata": true
		},
	...
	},
	"name": "SMAP_RSS_L2_SSS_V5",

**Comment by ymchenjpl** [comment]
@jamesfwood  FYI, the data provider has just started sending a newer version SMAP_RSS_L2_SSS_V6: https://jira.jpl.nasa.gov/browse/PODAAC-5997

**Comment by ymchenjpl** [comment]
Stepheny just fixed the Cumulus Forward-stream to re-enable Forge/TIG for SMAP_RSS_L2_SSS_V5.  Tim and Max will run the Backfill Tool to create the missing footprints/thumbnails since it was accidentally stopped on 12/5/23.

**Comment by ymchenjpl** [comment]
Tim and Max finished running the Backfill Tool on 2/28/24 to fill in the missing footprints/thumbnails for SMAP_RSS_L2_SSS_V5.
