### ISSUE TITLE
Test new l2ss-py and concise versions in HiTIDE and EDSC

### ISSUE THREAD

**Issue by jamesfwood** [podaac/hitide#61]

**Comment by jamesfwood** [comment]
@davidcolemanjpl Please test new versions of l2ss-py and concise in HiTIDE UI in UAT.
l2ss-py: 2.10.0-rcX
concise: 0.9.0rcX

Thanks!

**Comment by davidcolemanjpl** [comment]
HiTIDE UI (UAT) v4.17.2-RC.6
**l2ss-py:2.10.0rc8**
EDSC (UAT) - v24.2.2-5

HiTIDE UI (OPS) v4.17.1
**l2ss-py:2.10.0**
EDSC (OPS) - v24.2.1-2

Utilized **_SWOT_L2_LR_SSH_WINDWAVE_2.0_**  cloud collection for UAT/OPS validation:
UAT - C1261072648-POCLOUD
OPS - C2799465507-POCLOUD

**Test Complete** 


Can view respective harmony job statuses:
UAT -  https://harmony.uat.earthdata.nasa.gov/jobs/7cdb00c4-f448-45c1-9f41-5651c71be577
OPS -  https://harmony.earthdata.nasa.gov/jobs/bfba9fb9-bad2-44a3-9cb9-0ce8c07dc48e
